services:
  scraibe:
    image: scraibe-xpu:latest
    container_name: scraibe_xpu
    entrypoint: [ "/bin/bash" ]
    command: [ "-l" ]  # Login shell for interactive use
    volumes:
      - /tmp:/data
      - /opt/intel/oneapi/:/opt/intel/oneapi/  # Add this line
    devices:
      - /dev/dri:/dev/dri
    environment:
      - LD_LIBRARY_PATH=/opt/intel/oneapi/compiler/latest/lib/x64:/opt/intel/oneapi/mkl/latest/lib/x64:/opt/intel/oneapi/tbb/latest/lib/x64
      - SCRAIBE_TORCH_DEVICE=xpu
      - SYCL_DEVICE_FILTER=level_zero:gpu
      - HF_TOKEN=${HF_TOKEN}
      - IPEX_XPU_ONEDNN_LAYOUT=1
      - LIBVA_DRIVER_NAME=iHD
      - AUTOT_CACHE=/data/models/
    env_file:
      - .env
    stdin_open: true      # <- needed for interactive mode
    tty: true             # <- needed for interactive mode
    restart: no           # <- so it doesn’t restart on exit

